 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author alfianzack
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        MenuUtama = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSiswa = new javax.swing.JButton();
        btnGuru = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        MenuSiswa = new javax.swing.JPanel();
        btnMapel = new javax.swing.JButton();
        btnNilai = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pnlProfil = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textProfilSiswa = new javax.swing.JTextArea();
        pnlTmbahMapel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fisika = new javax.swing.JCheckBox();
        Biologi = new javax.swing.JCheckBox();
        kimia = new javax.swing.JCheckBox();
        btnTmbhMapel = new javax.swing.JButton();
        pnlNilai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaNilaiSiswa = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        MenuGuru = new javax.swing.JPanel();
        btnInputNilai = new javax.swing.JButton();
        btnTambahSiswa = new javax.swing.JButton();
        btnDaftarSiswa = new javax.swing.JButton();
        btnDaftarNilai = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnlProfilGuru = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textProfilGuru = new javax.swing.JTextArea();
        pnlInputNilai = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtInputQuis = new javax.swing.JTextField();
        txtInputTugas = new javax.swing.JTextField();
        txtInputUTS = new javax.swing.JTextField();
        txtInputUAS = new javax.swing.JTextField();
        btnMasukNilai = new javax.swing.JButton();
        cmbNamaSiswa = new javax.swing.JComboBox();
        cmbNamaMapel = new javax.swing.JComboBox();
        pnlTambahSiswa = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtInputNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtInputNIS = new javax.swing.JTextField();
        btnInputNamaSiswa = new javax.swing.JButton();
        pnlDaftarSiswa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDaftarSiswa = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        pnlDaftarNilai = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaDaftarNilai = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Input Nilai");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelUtama.setLayout(new javax.swing.OverlayLayout(PanelUtama));

        btnSiswa.setText("Menu Siswa");

        btnGuru.setText("Menu Guru");

        btnExit.setText("Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(btnGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setText("Nama Siswa");

        btnLogin.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(62, 82, Short.MAX_VALUE))
                    .addComponent(txtNama))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuUtamaLayout = new javax.swing.GroupLayout(MenuUtama);
        MenuUtama.setLayout(MenuUtamaLayout);
        MenuUtamaLayout.setHorizontalGroup(
            MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuUtamaLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        MenuUtamaLayout.setVerticalGroup(
            MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuUtamaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        PanelUtama.add(MenuUtama);

        btnMapel.setText("Tambah Mapel");

        btnNilai.setText("Lihat Nilai");

        Keluar.setText("Keluar");

        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Profil");

        textProfilSiswa.setColumns(20);
        textProfilSiswa.setRows(5);
        jScrollPane4.setViewportView(textProfilSiswa);

        javax.swing.GroupLayout pnlProfilLayout = new javax.swing.GroupLayout(pnlProfil);
        pnlProfil.setLayout(pnlProfilLayout);
        pnlProfilLayout.setHorizontalGroup(
            pnlProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilLayout.createSequentialGroup()
                .addGroup(pnlProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfilLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProfilLayout.setVerticalGroup(
            pnlProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(pnlProfil);

        jLabel2.setText("Pilihan Mata Pelajaran");

        Fisika.setText("Fisika");

        Biologi.setText("Biologi");

        kimia.setText("Kimia");

        btnTmbhMapel.setText("Tambah");

        javax.swing.GroupLayout pnlTmbahMapelLayout = new javax.swing.GroupLayout(pnlTmbahMapel);
        pnlTmbahMapel.setLayout(pnlTmbahMapelLayout);
        pnlTmbahMapelLayout.setHorizontalGroup(
            pnlTmbahMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTmbahMapelLayout.createSequentialGroup()
                .addGroup(pnlTmbahMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTmbahMapelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlTmbahMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Fisika, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlTmbahMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(kimia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Biologi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))))
                    .addGroup(pnlTmbahMapelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnTmbhMapel)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlTmbahMapelLayout.setVerticalGroup(
            pnlTmbahMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTmbahMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fisika)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Biologi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kimia)
                .addGap(18, 18, 18)
                .addComponent(btnTmbhMapel)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel3.add(pnlTmbahMapel);

        textAreaNilaiSiswa.setColumns(20);
        textAreaNilaiSiswa.setRows(5);
        jScrollPane1.setViewportView(textAreaNilaiSiswa);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nilai");

        javax.swing.GroupLayout pnlNilaiLayout = new javax.swing.GroupLayout(pnlNilai);
        pnlNilai.setLayout(pnlNilaiLayout);
        pnlNilaiLayout.setHorizontalGroup(
            pnlNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNilaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlNilaiLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNilaiLayout.setVerticalGroup(
            pnlNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNilaiLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(pnlNilai);

        javax.swing.GroupLayout MenuSiswaLayout = new javax.swing.GroupLayout(MenuSiswa);
        MenuSiswa.setLayout(MenuSiswaLayout);
        MenuSiswaLayout.setHorizontalGroup(
            MenuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        MenuSiswaLayout.setVerticalGroup(
            MenuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSiswaLayout.createSequentialGroup()
                .addGroup(MenuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuSiswaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuSiswaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnMapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNilai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Keluar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelUtama.add(MenuSiswa);

        btnInputNilai.setText("Input Nilai");

        btnTambahSiswa.setText("Tambah Siswa");

        btnDaftarSiswa.setText("Daftar Siswa");

        btnDaftarNilai.setText("Daftar Nilai");

        btnKembali.setText("Kembali");

        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Profil");

        textProfilGuru.setColumns(20);
        textProfilGuru.setRows(5);
        jScrollPane5.setViewportView(textProfilGuru);

        javax.swing.GroupLayout pnlProfilGuruLayout = new javax.swing.GroupLayout(pnlProfilGuru);
        pnlProfilGuru.setLayout(pnlProfilGuruLayout);
        pnlProfilGuruLayout.setHorizontalGroup(
            pnlProfilGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilGuruLayout.createSequentialGroup()
                .addGroup(pnlProfilGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfilGuruLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProfilGuruLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlProfilGuruLayout.setVerticalGroup(
            pnlProfilGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilGuruLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(pnlProfilGuru);

        jLabel6.setText("Nama");

        jLabel7.setText("Mapel");

        jLabel8.setText("Quis");

        jLabel9.setText("Tugas");

        jLabel10.setText("UTS");

        jLabel11.setText("UAS");

        btnMasukNilai.setText("Input");

        cmbNamaMapel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fisika", "Biologi", "Kimia" }));

        javax.swing.GroupLayout pnlInputNilaiLayout = new javax.swing.GroupLayout(pnlInputNilai);
        pnlInputNilai.setLayout(pnlInputNilaiLayout);
        pnlInputNilaiLayout.setHorizontalGroup(
            pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputNilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMasukNilai)
                    .addGroup(pnlInputNilaiLayout.createSequentialGroup()
                        .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInputQuis, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(txtInputTugas))
                        .addGap(26, 26, 26)
                        .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInputUTS, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(txtInputUAS)))
                    .addComponent(cmbNamaSiswa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbNamaMapel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlInputNilaiLayout.setVerticalGroup(
            pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputNilaiLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbNamaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtInputQuis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtInputUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtInputTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtInputUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnMasukNilai)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.add(pnlInputNilai);

        jLabel4.setText("Nama ");

        jLabel5.setText("NIS");

        btnInputNamaSiswa.setText("Tambah");

        javax.swing.GroupLayout pnlTambahSiswaLayout = new javax.swing.GroupLayout(pnlTambahSiswa);
        pnlTambahSiswa.setLayout(pnlTambahSiswaLayout);
        pnlTambahSiswaLayout.setHorizontalGroup(
            pnlTambahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahSiswaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlTambahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlTambahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInputNama)
                    .addComponent(txtInputNIS, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addGroup(pnlTambahSiswaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnInputNamaSiswa)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlTambahSiswaLayout.setVerticalGroup(
            pnlTambahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahSiswaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlTambahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlTambahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addComponent(btnInputNamaSiswa)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.add(pnlTambahSiswa);

        textAreaDaftarSiswa.setColumns(20);
        textAreaDaftarSiswa.setRows(5);
        jScrollPane2.setViewportView(textAreaDaftarSiswa);

        jLabel12.setText("Daftar Siswa");

        javax.swing.GroupLayout pnlDaftarSiswaLayout = new javax.swing.GroupLayout(pnlDaftarSiswa);
        pnlDaftarSiswa.setLayout(pnlDaftarSiswaLayout);
        pnlDaftarSiswaLayout.setHorizontalGroup(
            pnlDaftarSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarSiswaLayout.createSequentialGroup()
                .addGroup(pnlDaftarSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaftarSiswaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel12))
                    .addGroup(pnlDaftarSiswaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlDaftarSiswaLayout.setVerticalGroup(
            pnlDaftarSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarSiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.add(pnlDaftarSiswa);

        textAreaDaftarNilai.setColumns(20);
        textAreaDaftarNilai.setRows(5);
        jScrollPane3.setViewportView(textAreaDaftarNilai);

        jLabel13.setText("Daftar Nilai");

        javax.swing.GroupLayout pnlDaftarNilaiLayout = new javax.swing.GroupLayout(pnlDaftarNilai);
        pnlDaftarNilai.setLayout(pnlDaftarNilaiLayout);
        pnlDaftarNilaiLayout.setHorizontalGroup(
            pnlDaftarNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarNilaiLayout.createSequentialGroup()
                .addGroup(pnlDaftarNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaftarNilaiLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel13))
                    .addGroup(pnlDaftarNilaiLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlDaftarNilaiLayout.setVerticalGroup(
            pnlDaftarNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDaftarNilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.add(pnlDaftarNilai);

        javax.swing.GroupLayout MenuGuruLayout = new javax.swing.GroupLayout(MenuGuru);
        MenuGuru.setLayout(MenuGuruLayout);
        MenuGuruLayout.setHorizontalGroup(
            MenuGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuGuruLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(MenuGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambahSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInputNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDaftarSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDaftarNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuGuruLayout.setVerticalGroup(
            MenuGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuGuruLayout.createSequentialGroup()
                .addGroup(MenuGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuGuruLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnInputNilai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambahSiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDaftarSiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDaftarNilai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKembali))
                    .addGroup(MenuGuruLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        PanelUtama.add(MenuGuru);

        jMenu1.setText("File");

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        menuAbout.setText("About");
        jMenu2.add(menuAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MenuUtama.setVisible(true);
        MenuSiswa.setVisible(false);
        MenuGuru.setVisible(false);
        jPanel1.setVisible(false);
        txtNama.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Biologi;
    private javax.swing.JCheckBox Fisika;
    private javax.swing.JButton Keluar;
    private javax.swing.JPanel MenuGuru;
    private javax.swing.JPanel MenuSiswa;
    private javax.swing.JPanel MenuUtama;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JButton btnDaftarNilai;
    private javax.swing.JButton btnDaftarSiswa;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuru;
    private javax.swing.JButton btnInputNamaSiswa;
    private javax.swing.JButton btnInputNilai;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMapel;
    private javax.swing.JButton btnMasukNilai;
    private javax.swing.JButton btnNilai;
    private javax.swing.JButton btnSiswa;
    private javax.swing.JButton btnTambahSiswa;
    private javax.swing.JButton btnTmbhMapel;
    private javax.swing.JComboBox cmbNamaMapel;
    private javax.swing.JComboBox cmbNamaSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JCheckBox kimia;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JPanel pnlDaftarNilai;
    private javax.swing.JPanel pnlDaftarSiswa;
    private javax.swing.JPanel pnlInputNilai;
    private javax.swing.JPanel pnlNilai;
    private javax.swing.JPanel pnlProfil;
    private javax.swing.JPanel pnlProfilGuru;
    private javax.swing.JPanel pnlTambahSiswa;
    private javax.swing.JPanel pnlTmbahMapel;
    private javax.swing.JTextArea textAreaDaftarNilai;
    private javax.swing.JTextArea textAreaDaftarSiswa;
    private javax.swing.JTextArea textAreaNilaiSiswa;
    private javax.swing.JTextArea textProfilGuru;
    private javax.swing.JTextArea textProfilSiswa;
    private javax.swing.JTextField txtInputNIS;
    private javax.swing.JTextField txtInputNama;
    private javax.swing.JTextField txtInputQuis;
    private javax.swing.JTextField txtInputTugas;
    private javax.swing.JTextField txtInputUAS;
    private javax.swing.JTextField txtInputUTS;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    public void addListnener(ActionListener e) {
        btnSiswa.addActionListener(e);
        btnExit.addActionListener(e);
        btnGuru.addActionListener(e);
        txtNama.addActionListener(e);
        btnLogin.addActionListener(e);
        menuAbout.addActionListener(e);
        //MenuSiswa
        Keluar.addActionListener(e);
        btnMapel.addActionListener(e);
        btnTmbhMapel.addActionListener(e);
        btnNilai.addActionListener(e);
        //MenuGuru
        btnDaftarNilai.addActionListener(e);
        btnInputNamaSiswa.addActionListener(e);
        btnDaftarSiswa.addActionListener(e);
        btnInputNilai.addActionListener(e);
        btnTambahSiswa.addActionListener(e);
        btnKembali.addActionListener(e);
        btnMasukNilai.addActionListener(e);
        txtInputNama.addActionListener(e);
        txtInputNIS.addActionListener(e);
        //txtInputNamaNilai.addActionListener(e);
        //txtInputMapelNilai.addActionListener(e);
        txtInputQuis.addActionListener(e);
        txtInputTugas.addActionListener(e);
        txtInputUAS.addActionListener(e);
        txtInputUTS.addActionListener(e);
        cmbNamaSiswa.addActionListener(e);
        
    }

    Mapel m;
    String nama = null;
    String nis = null;
    Guru g;
    Siswa tempSiswa;
    
    
    public void setModel(Guru g) {
        this.g = g;
        Controller c = new Controller();
        jPanel1.setVisible(false);
        MenuUtama.setVisible(true);
        MenuSiswa.setVisible(false);
        MenuGuru.setVisible(false);
        

    }

    private class Controller implements ActionListener {

        public Controller() {
            addListnener(this);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            Object source = e.getSource();
            if (source.equals(btnExit)) {
                System.exit(0);
            } else if (source.equals(btnSiswa)) {
                jPanel1.setVisible(true);
            } else if (source.equals(btnLogin)) {
                String i = txtNama.getText();
                tempSiswa = g.cariSiswa(i);
                try {
                    tempSiswa.getNama().equals(i);
                    MenuSiswa.setVisible(true);
                    MenuUtama.setVisible(false);
                    MenuGuru.setVisible(false);
                    pnlTmbahMapel.setVisible(false);
                    pnlNilai.setVisible(false);
                    pnlProfil.setVisible(true);
                    textProfilSiswa.setText("Nama : "+tempSiswa.getNama()+"\nNIS : "+tempSiswa.getNis());
                } catch (NullPointerException npe) {
                    JOptionPane.showConfirmDialog(null, "Nama tidak ada ", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);

                }
            } else if (source.equals(Keluar)) {
                MenuUtama.setVisible(true);
                MenuSiswa.setVisible(false);
                jPanel1.setVisible(false);
                txtNama.setText("");

            } else if (source.equals(btnMapel)) {
                pnlTmbahMapel.setVisible(true);
                pnlNilai.setVisible(false);
                pnlProfil.setVisible(false);

            } else if (source.equals(btnTmbhMapel)) {

                try {

                    if (Fisika.isSelected()) {
                        m = tempSiswa.cekMapel("Fisika");
                        if (m == null) {
                            Mapel m1 = new Mapel("Fisika");
                            tempSiswa.ambilMapel(m1);
                        } else {
                            throw new Exception("Mapel Fisika sudah dipilih");
                        }
                    }
                    if (Biologi.isSelected()) {
                        m = tempSiswa.cekMapel("Biologi");
                        if (m == null) {
                            Mapel m1 = new Mapel("Biologi");
                            tempSiswa.ambilMapel(m1);
                        } else {
                            throw new Exception("Mapel Biologi sudah dipilih");
                        }
                    }
                    if (kimia.isSelected()) {
                        m = tempSiswa.cekMapel("Kimia");
                        if (m == null) {
                            Mapel m1 = new Mapel("Kimia");
                            tempSiswa.ambilMapel(m1);
                        } else {
                            throw new Exception("Mapel Kimia sudah dipilih");
                        }
                    }
                } catch (ArrayIndexOutOfBoundsException aie) {
                    JOptionPane.showConfirmDialog(null, "Mapel melebihi ", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showConfirmDialog(null, ex.getMessage(), "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                } finally {
                    Fisika.setSelected(false);
                    kimia.setSelected(false);
                    Biologi.setSelected(false);
                }

            } else if (source.equals(btnNilai)) {
                pnlTmbahMapel.setVisible(false);
                pnlNilai.setVisible(true);
                pnlProfil.setVisible(false);
                textAreaNilaiSiswa.setText(tempSiswa.viewAllScore());
                textAreaNilaiSiswa.setCaretPosition(0);
                
            } else if (source.equals(btnGuru)) {
                MenuGuru.setVisible(true);
                MenuSiswa.setVisible(false);
                MenuUtama.setVisible(false);
                pnlInputNilai.setVisible(false);
                pnlTambahSiswa.setVisible(false);
                pnlDaftarSiswa.setVisible(false);
                pnlDaftarNilai.setVisible(false);
                pnlProfilGuru.setVisible(true);
                textProfilGuru.setText("Nama : "+g.getNama()+"\nNIP : "+g.getNip());

            } else if (source.equals(btnInputNilai)) {
                pnlInputNilai.setVisible(true);
                pnlTambahSiswa.setVisible(false);
                pnlDaftarSiswa.setVisible(false);
                pnlDaftarNilai.setVisible(false);
                pnlProfilGuru.setVisible(false);
                //txtInputMapelNilai.setText("");
                //txtInputNamaNilai.setText("");
                txtInputQuis.setText("0");
                txtInputTugas.setText("0");
                txtInputUAS.setText("0");
                txtInputUTS.setText("0");

            } else if (source.equals(btnMasukNilai)) {
                try {
                    tempSiswa = g.cariSiswa((String)cmbNamaSiswa.getSelectedItem());
                    //tempSiswa = g.cariSiswa(txtInputNamaNilai.getText());
                    int uts = Integer.parseInt(txtInputUTS.getText());
                    int uas = Integer.parseInt(txtInputUAS.getText());
                    int quis = Integer.parseInt(txtInputQuis.getText());
                    int tugas = Integer.parseInt(txtInputTugas.getText());
                    //tempSiswa.setNilai(txtInputMapelNilai.getText(), uts, uas, quis, tugas);
                    m = tempSiswa.cekMapel((String)cmbNamaMapel.getSelectedItem());
                    tempSiswa.setNilai(m.getNamaMapel(), uts, uas, quis, tugas);
                } catch (NullPointerException noe) {
                    JOptionPane.showConfirmDialog(null, "Mata Pelajaran tidak diambil", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                } finally {
                    //txtInputMapelNilai.setText("");
                    //txtInputNamaNilai.setText("");
                    txtInputQuis.setText("0");
                    txtInputTugas.setText("0");
                    txtInputUAS.setText("0");
                    txtInputUTS.setText("0");
                }

            } else if (source.equals(btnTambahSiswa)) {
                txtInputNama.setText("");
                txtInputNIS.setText("");
                pnlInputNilai.setVisible(false);
                pnlTambahSiswa.setVisible(true);
                pnlDaftarSiswa.setVisible(false);
                pnlDaftarNilai.setVisible(false);
                pnlProfilGuru.setVisible(false);

            } else if (source.equals(btnDaftarSiswa)) {
                pnlInputNilai.setVisible(false);
                pnlTambahSiswa.setVisible(false);
                pnlDaftarSiswa.setVisible(true);
                pnlDaftarNilai.setVisible(false);
                pnlProfilGuru.setVisible(false);
                textAreaDaftarSiswa.setText(g.viewSiswa());
                textAreaDaftarSiswa.setCaretPosition(0);

            } else if (source.equals(btnDaftarNilai)) {
                pnlInputNilai.setVisible(false);
                pnlTambahSiswa.setVisible(false);
                pnlDaftarSiswa.setVisible(false);
                pnlDaftarNilai.setVisible(true);
                pnlProfilGuru.setVisible(false);
                textAreaDaftarNilai.setText(g.viewNilai());
                textAreaDaftarNilai.setCaretPosition(0);

            } else if (source.equals(btnKembali)) {
                MenuUtama.setVisible(true);
                MenuSiswa.setVisible(false);
                MenuGuru.setVisible(false);
                jPanel1.setVisible(false);
                txtNama.setText("");

            } else if (source.equals(btnInputNamaSiswa)) {
                nama = txtInputNama.getText();
                cmbNamaSiswa.addItem(nama);
                nis = txtInputNIS.getText();
                Siswa tempNis = g.cekNis(nis);
                if (tempNis == null) {
                    try {
                        tempSiswa = new Siswa(nama, nis);
                        g.addSiswa(tempSiswa);

                    } catch (NullPointerException npe) {
                        JOptionPane.showConfirmDialog(null, "Form nama dan nis tidak boleh kosong", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    } catch (ArrayIndexOutOfBoundsException aio) {
                        JOptionPane.showConfirmDialog(null, "Siswa melebihi kelas", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    } finally {
                        txtInputNama.setText("");
                        txtInputNIS.setText("");
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "NIS sudah terpakai", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }

            }else if (source.equals(menuAbout)){
                JOptionPane.showConfirmDialog(null, "Aplikasi Input Mata Pelajaran \n   Kelompok6 \nCopyRigth@2015", "About", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

}
